<a href="https://colab.research.google.com/github/Pavimohan9/Task-7---11/blob/main/Task_7_11_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data.csv

Step 1: Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
import os

**Step 2: Importing dataset*

In [ ]:
dataset = pd.read_csv('/content/Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Step 3: Handling the missing data*

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Step 4: Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop= 'first'), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 0.0 44.0 72000.0]
 [0.0 1.0 27.0 48000.0]
 [1.0 0.0 30.0 54000.0]
 [0.0 1.0 38.0 61000.0]
 [1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 35.0 58000.0]
 [0.0 1.0 38.77777777777778 52000.0]
 [0.0 0.0 48.0 79000.0]
 [1.0 0.0 50.0 83000.0]
 [0.0 0.0 37.0 67000.0]]


Step 5: Creating a dummy variable

In [ ]:
pd.get_dummies(dataset)

Age   Salary  Country_France  Country_Germany  Country_Spain  \
0  44.0  72000.0               1                0              0   
1  27.0  48000.0               0                0              1   
2  30.0  54000.0               0                1              0   
3  38.0  61000.0               0                0              1   
4  40.0      NaN               0                1              0   
5  35.0  58000.0               1                0              0   
6   NaN  52000.0               0                0              1   
7  48.0  79000.0               1                0              0   
8  50.0  83000.0               0                1              0   
9  37.0  67000.0               1                0              0   

   Purchased_No  Purchased_Yes  
0             1              0  
1             0              1  
2             1              0  
3             1              0  
4             0              1  
5             0              1  
6             1              0  
7             0              1  
8             1              0  
9             0              1

Step 6: Splitting the datasets into training sets and Test sets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 44.0 72000.0]
 [0.0 1.0 38.0 61000.0]
 [0.0 1.0 27.0 48000.0]
 [0.0 0.0 48.0 79000.0]
 [1.0 0.0 50.0 83000.0]
 [0.0 0.0 35.0 58000.0]]


In [ ]:
print(y_train)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes']


In [ ]:
print(y_test)

['No' 'Yes']


Step 7: Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 2:] = sc.fit_transform(X_train[:, 2:])
X_test[:, 2:] = sc.transform(X_test[:, 2:])

In [ ]:
print(X_train)

[[0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [0.0 0.0 1.1475343068237058 1.232653363453549]
 [1.0 0.0 1.4379472069688968 1.5749910381638885]
 [0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [0.0 0.0 -0.44973664397484414 0.2056403393225306]]
